### ISSUE TITLE
deleted a commit using mixed mode and want to get it back

### ISSUE THREAD

**Issue by jevan13** [nus-cs2103-AY2425S1/forum#142]
hi guys
i was trying to undo a commit as i had named it wrongly using this instruction:
"To undo the last commit, right-click on the commit just before it, and choose Reset current branch to this commit.

In the next dialog, choose the mode Mixed - keep working copy but reset index option. This will make the offending commit disappear but will keep the changes that you included in that commit intact."

however i then pushed and now my work done on intellij is also back to the previous commit, without all my recent work.
 is there any way to get it back :(

thanks in advance

**Comment by jevan13** [comment]
<img width="1512" alt="Screenshot 2024-08-30 at 10 01 51 PM" src="https://github.com/user-attachments/assets/8e5faca2-a9e7-4d31-bce3-18a8a873bc7f">

**Comment by damithc** [comment]
> In the next dialog, choose the mode Mixed - keep working copy but reset index option. This will make the offending commit disappear but will keep the changes that you included in that commit intact."

@jevan13 After doing this, were you able to see the changes you did in the last commit (the one you un-did) as unstaged changes? If the answer is 'no', you might have chosen the 'hard reset' option by mistake, wiping out the last commit entirely.

**Comment by jevan13** [comment]
@damithc 

hi prof
the changes are not there in my unstaged changes anymore but im very sure i chose the mixed option. i also pushed it, did that delete my changes permanently? i googled and some people are saying to run git reflog to recover deleted commits, and i have ran it but it did not provide any SHAs for me to reset to

https://jira.atlassian.com/browse/SRCTREE-1364

**Comment by riccoljy** [comment]
Hi!

Which branch was the deleted commit on? Was the commit pushed before you deleted it? If it was, then there's a chance you could retrieve it. I'm trying to see from your repo but I'm not sure haha.... 

If the commits were local and not pushed, I believe there is a chance that your IDE might have shelved them...

**Comment by jevan13** [comment]
@riccoljy Hi I pushed after i deleted the commit

**Comment by tohhengxing** [comment]
Regardless of what you did, the git SHAs will still persist in the git DB for a period of time before the git GC removes it permanently.

The standard way of retrieving is to use `reflog` for that specific branch and find the SHA.

**Comment by Timenikhil** [comment]
IntelliJ has local history, right click on file, select local history as shown from option menu, click on show history and revert to your change. Note this is different from git and is IntelliJ's autosave feature. This saves all changes even uncommitted ones and shows all the way back to class creation. If you did not use the IDE to code, look for stashed changes and please start using the IDE in the future.

<img width="317" alt="image" src="https://github.com/user-attachments/assets/b9345d3a-8a87-4d69-8c90-b2813e497d25">

<img width="449" alt="image" src="https://github.com/user-attachments/assets/72f413bc-d6d4-43c6-b758-bbcf810984bf">

**Comment by Timenikhil** [comment]
By default, Local History is configured to store revisions for the last 5 working days (that is, days when the file was modified). In the Settings dialog ( Ctrl Alt 0S ) , go to Advanced Settings. In the IDE section, provide the desired retention period value in the Duration of storing changes in Local History field.

**Comment by jevan13** [comment]
@Timenikhil 
hi thanks! i found it in the out folder with some parts of the code changed (eg variable names and conditions) other than that, i got it back :)
